# Generated by Django 4.1 on 2022-08-08 08:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('active_comment_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
